export const SITE = {
  name: 'Joolomee',
  tagline: 'Remember me, Joolomee.',
  promise: 'Every brand deserves a (re)start.',
  domain: 'joolomee.com',
  email: 'rememberme@joolomee.com',
  // Phone kept for schema + WhatsApp deep-link only — never rendered in UI.
  phone: '+351 928 289 201',
  whatsapp: '351928289201',
  location: 'Portimão, Algarve, Portugal',
  country: 'PT',
  region: 'Algarve',
  geo: { lat: 37.1356, lon: -8.5379 },
  linkedin: 'https://www.linkedin.com/in/joana-lopes-mesquita',
  behance: 'https://www.behance.net/joolomee',
  instagram: 'https://www.instagram.com/joolomee',
};

export const NAV_LINKS = [
  { href: '/work', key: 'work' },
  { href: '/services', key: 'services' },
  { href: '/about', key: 'about' },
];

export const CLIENTS = [
  'CogniFit',
  "D'ALMA® FarmLiving",
  'TCPI International',
  'DualClinic Saldanha',
  'CarlaGonçalves',
  'Agência Modal',
  'Albinet',
];

export const SERVICES = [
  { n: '01', key: 'srv01' },
  { n: '02', key: 'srv02' },
  { n: '03', key: 'srv03' },
  { n: '04', key: 'srv04' },
  { n: '05', key: 'srv05' },
  { n: '06', key: 'srv06' },
  { n: '07', key: 'srv07' },
];

export type Project = {
  slug: string; client: string;
  titleKey: string; categoryKey: string;
  year: string; tags: string[]; hero: string; accent: string;
};

export const WORK: Project[] = [
  {
    slug: 'cognifit',
    client: 'CogniFit',
    titleKey: 'workCognifitTitle',
    categoryKey: 'catWeb',
    year: '2022 — 2026',
    tags: ['Landing Pages', 'Game UI', 'Email Campaigns', 'Marketing Design'],
    hero: '/work/cognifit-mindfit-hero.png',
    accent: 'from-[#0B3B8C] via-[#1A73E8] to-[#6FB6FF]',
  },
  {
    slug: 'dalma-farmliving',
    client: "D'ALMA® FarmLiving",
    titleKey: 'workDalmaTitle',
    categoryKey: 'catBrand',
    year: '2025',
    tags: ['Logo', 'Brand System', 'Packaging', 'Applications'],
    hero: '/work/dalma-mel-full.png',
    accent: 'from-[#2F4F4A] via-[#5C7A70] to-[#B89F6A]',
  },
  {
    slug: 'tcpi-international',
    client: 'TCPI International',
    titleKey: 'workTcpiTitle',
    categoryKey: 'catMotion',
    year: '2026',
    tags: ['21-slide Deck', 'Motion Video', 'Brand Design'],
    hero: '',
    accent: 'from-[#0F0F10] via-[#2A2A2E] to-[#5C5C66]',
  },
  {
    slug: 'dualclinic-saldanha',
    client: 'DualClinic Saldanha',
    titleKey: 'workDualTitle',
    categoryKey: 'catCreative',
    year: '2022 — 2023',
    tags: ['Social Media', 'B2C Campaigns', 'Ad Design'],
    hero: '',
    accent: 'from-[#7A1F4F] via-[#C8477E] to-[#FFB3D1]',
  },
  {
    slug: 'carlagoncalves',
    client: 'CarlaGonçalves',
    titleKey: 'workCarlaTitle',
    categoryKey: 'catBrand',
    year: '2019 — ongoing',
    tags: ['Concept', 'Logo', 'Visual Identity', 'Applications'],
    hero: '',
    accent: 'from-[#2A1B3D] via-[#6B4E8F] to-[#E8C4E8]',
  },
  {
    slug: 'agencia-modal',
    client: 'Agência Modal',
    titleKey: 'workModalTitle',
    categoryKey: 'catGraphic',
    year: '2024',
    tags: ['Banners', 'Posters', 'Photo Editing', 'Merch'],
    hero: '',
    accent: 'from-[#1F3A5F] via-[#4C6B8A] to-[#A8C6E8]',
  },
  {
    slug: 'albinet',
    client: 'Albinet — Digital Innovation',
    titleKey: 'workAlbinetTitle',
    categoryKey: 'catMulti',
    year: '2021 — 2022',
    tags: ['UX/UI', 'A/B Testing', 'Landing Pages', '3D · Blender', 'AutoCAD'],
    hero: '',
    accent: 'from-[#0A1F3A] via-[#1A4580] to-[#3D7BC8]',
  },
];

export const STATS = [
  { n: '7+', labelKey: 'statYears' },
  { n: '10+', labelKey: 'statBrands' },
  { n: '3', labelKey: 'statCountries' },
  { n: '3', labelKey: 'statLangsSpoken' },
];

export const PROCESS = [
  { n: '01', key: 'p01' },
  { n: '02', key: 'p02' },
  { n: '03', key: 'p03' },
  { n: '04', key: 'p04' },
  { n: '05', key: 'p05' },
];

/* ---------------- Quiz ----------------
   Five questions; each answer maps to a type.
   A=Starter, B=Rebuilder, C=Scaler, D=Editorial
*/
export const QUIZ = {
  questions: [
    { key: 'q1', options: [
      { key: 'q1a', type: 'A' }, { key: 'q1b', type: 'B' },
      { key: 'q1c', type: 'C' }, { key: 'q1d', type: 'D' },
    ]},
    { key: 'q2', options: [
      { key: 'q2a', type: 'A' }, { key: 'q2b', type: 'B' },
      { key: 'q2c', type: 'C' }, { key: 'q2d', type: 'D' },
    ]},
    { key: 'q3', options: [
      { key: 'q3a', type: 'A' }, { key: 'q3b', type: 'B' },
      { key: 'q3c', type: 'C' }, { key: 'q3d', type: 'D' },
    ]},
    { key: 'q4', options: [
      { key: 'q4a', type: 'A' }, { key: 'q4b', type: 'B' },
      { key: 'q4c', type: 'C' }, { key: 'q4d', type: 'D' },
    ]},
    { key: 'q5', options: [
      { key: 'q5a', type: 'A' }, { key: 'q5b', type: 'B' },
      { key: 'q5c', type: 'C' }, { key: 'q5d', type: 'D' },
    ]},
  ],
  types: ['A', 'B', 'C', 'D'] as const,
};

// i18n ----------------------------------------------------------------
export const LOCALES = ['en', 'pt', 'es', 'fr', 'de', 'it', 'nl'] as const;
export type Locale = (typeof LOCALES)[number];

export const LOCALE_META: Record<Locale, { label: string; native: string; flag: string; countries: string[] }> = {
  en: { label: 'English',    native: 'English',    flag: '🇬🇧', countries: ['GB','US','IE','AU','CA','NZ'] },
  pt: { label: 'Portuguese', native: 'Português',  flag: '🇵🇹', countries: ['PT','BR','AO','MZ','CV'] },
  es: { label: 'Spanish',    native: 'Español',    flag: '🇪🇸', countries: ['ES','MX','AR','CL','CO','PE'] },
  fr: { label: 'French',     native: 'Français',   flag: '🇫🇷', countries: ['FR','BE','CH','LU','MC'] },
  de: { label: 'German',     native: 'Deutsch',    flag: '🇩🇪', countries: ['DE','AT','CH','LI'] },
  it: { label: 'Italian',    native: 'Italiano',   flag: '🇮🇹', countries: ['IT','SM','VA'] },
  nl: { label: 'Dutch',      native: 'Nederlands', flag: '🇳🇱', countries: ['NL','BE','SR'] },
};

type T = Record<string, string>;

const en: T = {
  // nav
  navWork: 'Work', navServices: 'Services', navAbout: 'About', navContact: 'Contact',
  navQuiz: 'Are we a fit?',
  navCta: "Let's talk",
  // hero
  status: 'Available for new projects — 2026',
  heroLine1: 'Remember me,',
  heroLine2: 'Joolomee.',
  heroSub: 'Full Stack Designer & Creative Director based in Portimão. I build brands from the ground up — and rebuild them to be unforgettable.',
  ctaStart: 'Start a project', ctaWork: 'View work',
  // manifesto
  manifestoLabel: 'Manifesto',
  manifesto1: 'Every brand deserves', manifesto2: 'a (re)start.',
  manifesto3: 'A thread. A story. A beginning. That is the Joolomee way.',
  // services
  servicesLabel: 'Services', servicesTitle: 'What I do.', servicesCta: 'Explore all services',
  srv01: 'Brand Strategy & Identity',
  srv01d: 'Naming, positioning, architecture, logo, complete visual system and brand book. A brand from the ground up.',
  srv02: 'Brand Refresh & Rebrand',
  srv02d: 'Reformulating existing brands to make them memorable, relevant, and ready for the next chapter.',
  srv03: 'Web Design & Development',
  srv03d: 'Native sites (Next.js / HTML-CSS-JS) and Webflow — corporate, portfolio, landing pages, e-commerce.',
  srv04: 'UI/UX Design',
  srv04d: 'Interfaces for apps, dashboards, and platforms. Figma, A/B testing, responsive systems.',
  srv05: 'Social Media & Marketing Design',
  srv05d: 'Templates, B2C campaigns, stories, banners, and ads across Instagram, LinkedIn, and Facebook.',
  srv06: 'Creative Direction',
  srv06d: 'Visual direction for campaigns, project identity, and production supervision.',
  srv07: 'Presentation & Motion',
  srv07d: 'Pitch decks, corporate presentations, video editing, motion graphics.',
  // process
  processLabel: 'Process', processTitle: 'How I work.',
  processSub: 'Every project follows the same five beats — tailored to fit your brand, not forced.',
  p01: 'Listen', p01d: 'A free 30-min discovery call. I want to understand the story before I design the shape.',
  p02: 'Map', p02d: 'Strategy document — objectives, audience, competitors, positioning. Nothing moves without it.',
  p03: 'Explore', p03d: 'Two to three visual directions. You react, we refine. No ego, no fluff.',
  p04: 'Craft', p04d: 'Full design system or build — every pixel, every interaction, intentional.',
  p05: 'Launch', p05d: 'Delivery, handoff, and 30 days of care. Then I stay available — always one message away.',
  // work
  workLabel: 'Selected Work', workTitle: 'Featured projects.', workCta: 'View all work',
  catWeb: 'Web Design & Development', catBrand: 'Brand Identity', catMotion: 'Presentation & Motion',
  catCreative: 'Creative Direction', catGraphic: 'Graphic Design', catMulti: 'Multi-discipline',
  workCognifitTitle: 'Full Stack Design — Web, Campaigns & Marketing',
  workDalmaTitle: 'Luxury Farm Hotel & Bio Commerce',
  workTcpiTitle: 'Corporate Communications — Deck & Motion',
  workDualTitle: 'Aesthetic Clinic Campaigns',
  workCarlaTitle: 'Estética & Bem-Estar — Brand Identity',
  workModalTitle: 'Porto Event — Campaign & Merchandise',
  workAlbinetTitle: 'UX/UI, Web & Interior Design',
  // about
  aboutLabel: 'About',
  aboutLead: "I'm Joana — designer, developer, and creative director. I work at the intersection of brand, code, and craft.",
  aboutBody: 'Seven years building visual systems for brands that want to matter. From cognitive-health platforms translated into 22 languages, to luxury farm hotels, to corporate decks — every project is treated as a portfolio piece.',
  aboutCta: 'More about me',
  statYears: 'Years', statBrands: 'Brands', statCountries: 'Countries',
  statLangs: 'Languages', statLangsSpoken: 'Languages · PT · EN · ES',
  // contact
  contactLabel: 'Contact',
  contactTitle1: "Let's build", contactTitle2: 'something', contactTitle3: 'extraordinary.',
  contactSub: 'Available for new projects — remote worldwide. Full stack from concept to launch.',
  contactEmailLabel: 'Email', contactWhatsLabel: 'WhatsApp',
  contactWhatsCta: 'Direct message',
  // quiz
  quizLabel: 'Quick quiz · 60 seconds',
  quizTitle: 'Are we a fit?',
  quizSub: 'Five questions. Then I tell you exactly how I can help — no sales pitch.',
  quizStart: 'Start the quiz',
  quizNext: 'Next', quizBack: 'Back', quizRestart: 'Retake',
  quizResult: 'You are a',
  q1: 'Where are you in your brand journey?',
  q1a: 'Just starting — no brand yet.', q1b: 'I have a brand, but it no longer fits.',
  q1c: 'Solid brand, but I need to scale.', q1d: 'I have the brand, I just want beautiful collateral.',
  q2: 'What scares you the most right now?',
  q2a: 'Not knowing where to begin.', q2b: 'Looking outdated next to the competition.',
  q2c: 'Inconsistency across channels.', q2d: 'Producing content at pace without losing quality.',
  q3: 'Budget comfort zone?',
  q3a: 'Lean & scrappy — bootstrapping.', q3b: 'Mid — ready to invest in a refresh.',
  q3c: 'Invested — we think brand = growth.', q3d: 'Project-based retainer.',
  q4: 'Timeline?',
  q4a: 'Six to eight weeks for v1.', q4b: 'Four to six weeks — we are moving.',
  q4c: 'Three-month system.', q4d: 'Ongoing — weekly output.',
  q5: 'Who decides?',
  q5a: 'Me, myself and I.', q5b: 'Me + a partner.',
  q5c: 'Team with a head of brand/marketing.', q5d: 'Board-approved direction.',
  resultA: 'Starter',
  resultAd: 'You need a brand from zero — naming, identity, first website, and the confidence to go to market. Ideal fit: Package 01 (Brand Strategy & Identity) + Package 03 (Web).',
  resultB: 'Rebuilder',
  resultBd: 'You have history and traction — we keep the soul, change the clothes. Ideal fit: Package 02 (Brand Refresh) + Package 03 (Web) + Package 05 (Social).',
  resultC: 'Scaler',
  resultCd: 'You have a brand that works — you need a system that scales without breaking. Ideal fit: Package 01, 03 and 06 combined — a design language and creative direction as an ongoing layer.',
  resultD: 'Editorial',
  resultDd: 'Beautiful, editorial collateral — decks, campaigns, motion. Ideal fit: Package 05, 06 and 07.',
  resultCta: 'Book a discovery call',
};

const pt: T = {
  navWork: 'Trabalho', navServices: 'Serviços', navAbout: 'Sobre', navContact: 'Contacto',
  navQuiz: 'Damos match?',
  navCta: 'Falar',
  status: 'Disponível para novos projetos — 2026',
  heroLine1: 'Remember me,', heroLine2: 'Joolomee.',
  heroSub: 'Full Stack Designer e Diretora Criativa, em Portimão. Construo marcas de raiz — e reconstruo-as para serem memoráveis.',
  ctaStart: 'Começar um projeto', ctaWork: 'Ver trabalhos',
  manifestoLabel: 'Manifesto',
  manifesto1: 'Cada marca merece', manifesto2: 'um (re)começo.',
  manifesto3: 'Um fio. Uma história. Um princípio. É assim o Joolomee.',
  servicesLabel: 'Serviços', servicesTitle: 'O que faço.', servicesCta: 'Ver todos os serviços',
  srv01: 'Estratégia & Identidade de Marca',
  srv01d: 'Naming, posicionamento, arquitetura, logo, sistema visual completo e brand book. Uma marca de raiz.',
  srv02: 'Refresh & Rebrand',
  srv02d: 'Reformular marcas existentes para serem memoráveis, relevantes e prontas para o próximo capítulo.',
  srv03: 'Web Design & Desenvolvimento',
  srv03d: 'Sites nativos (Next.js / HTML-CSS-JS) e Webflow — corporativos, portfolio, landing pages, e-commerce.',
  srv04: 'UI/UX Design',
  srv04d: 'Interfaces para apps, dashboards e plataformas. Figma, testes A/B, sistemas responsivos.',
  srv05: 'Social Media & Marketing Design',
  srv05d: 'Templates, campanhas B2C, stories, banners e ads em Instagram, LinkedIn e Facebook.',
  srv06: 'Direção Criativa',
  srv06d: 'Direção visual de campanhas, identidade de projetos e supervisão de produção.',
  srv07: 'Apresentações & Motion',
  srv07d: 'Pitch decks, apresentações corporativas, edição de vídeo e motion graphics.',
  processLabel: 'Processo', processTitle: 'Como trabalho.',
  processSub: 'Cada projeto segue os mesmos cinco passos — feitos à medida da sua marca, nunca à força.',
  p01: 'Ouvir', p01d: 'Discovery call gratuita de 30 min. Quero entender a história antes de desenhar a forma.',
  p02: 'Mapear', p02d: 'Documento estratégico — objetivos, público, concorrência, posicionamento. Nada avança sem isto.',
  p03: 'Explorar', p03d: 'Duas a três direções visuais. Você reage, nós refinamos. Sem ego, sem ruído.',
  p04: 'Executar', p04d: 'Sistema de design completo ou build — cada pixel, cada interação, intencional.',
  p05: 'Lançar', p05d: 'Entrega, handoff e 30 dias de acompanhamento. Depois fico disponível — sempre à distância de uma mensagem.',
  workLabel: 'Trabalho Selecionado', workTitle: 'Projetos em destaque.', workCta: 'Ver todos os trabalhos',
  catWeb: 'Web Design & Dev', catBrand: 'Identidade de Marca', catMotion: 'Apresentação & Motion',
  catCreative: 'Direção Criativa', catGraphic: 'Design Gráfico', catMulti: 'Multidisciplinar',
  workCognifitTitle: 'Full Stack Design — Web, Campanhas & Marketing',
  workDalmaTitle: 'Hotel Rural de Luxo & Comércio Bio',
  workTcpiTitle: 'Comunicação Corporativa — Deck & Motion',
  workDualTitle: 'Campanhas para Clínica Estética',
  workCarlaTitle: 'Estética & Bem-Estar — Identidade',
  workModalTitle: 'Evento no Porto — Campanha & Merch',
  workAlbinetTitle: 'UX/UI, Web & Design de Interiores',
  aboutLabel: 'Sobre',
  aboutLead: 'Sou a Joana — designer, developer e diretora criativa. Trabalho na interseção entre marca, código e detalhe.',
  aboutBody: 'Sete anos a construir sistemas visuais para marcas que querem importar. De plataformas de saúde cognitiva traduzidas em 22 línguas, a hotéis rurais de luxo, a decks corporativos — cada projeto é tratado como uma peça de portfolio.',
  aboutCta: 'Saber mais sobre mim',
  statYears: 'Anos', statBrands: 'Marcas', statCountries: 'Países',
  statLangs: 'Idiomas', statLangsSpoken: 'Idiomas · PT · EN · ES',
  contactLabel: 'Contacto',
  contactTitle1: 'Vamos construir', contactTitle2: 'algo', contactTitle3: 'extraordinário.',
  contactSub: 'Disponível para novos projetos — remoto mundialmente. Full stack do conceito ao lançamento.',
  contactEmailLabel: 'Email', contactWhatsLabel: 'WhatsApp',
  contactWhatsCta: 'Enviar mensagem',
  quizLabel: 'Mini-quiz · 60 segundos',
  quizTitle: 'Damos match?',
  quizSub: 'Cinco perguntas. No fim digo exatamente como posso ajudar — sem discurso comercial.',
  quizStart: 'Começar',
  quizNext: 'Seguinte', quizBack: 'Voltar', quizRestart: 'Repetir',
  quizResult: 'És um(a)',
  q1: 'Em que ponto está a tua marca?',
  q1a: 'A começar — ainda não tenho marca.', q1b: 'Tenho marca, mas já não me serve.',
  q1c: 'Marca sólida, mas preciso escalar.', q1d: 'Tenho marca, só quero peças bonitas.',
  q2: 'O que mais te assusta agora?',
  q2a: 'Não saber por onde começar.', q2b: 'Parecer desatualizada face à concorrência.',
  q2c: 'Inconsistência em todos os canais.', q2d: 'Produzir conteúdo a ritmo sem perder qualidade.',
  q3: 'Zona de conforto de orçamento?',
  q3a: 'Enxuto — bootstrapping.', q3b: 'Intermédio — pronto para investir num refresh.',
  q3c: 'Investido — marca = crescimento.', q3d: 'Avença por projeto.',
  q4: 'Timeline?',
  q4a: 'Seis a oito semanas para v1.', q4b: 'Quatro a seis semanas — estamos a correr.',
  q4c: 'Sistema de três meses.', q4d: 'Contínuo — output semanal.',
  q5: 'Quem decide?',
  q5a: 'Só eu.', q5b: 'Eu + um sócio.',
  q5c: 'Equipa com responsável de marca/marketing.', q5d: 'Direção aprovada por board.',
  resultA: 'Starter',
  resultAd: 'Precisas de uma marca de raiz — naming, identidade, primeiro site e confiança para ir ao mercado. Ideal: Pacote 01 (Estratégia & Identidade) + Pacote 03 (Web).',
  resultB: 'Rebuilder',
  resultBd: 'Tens história e tração — mantemos a alma, mudamos a roupa. Ideal: Pacote 02 (Rebrand) + Pacote 03 (Web) + Pacote 05 (Social).',
  resultC: 'Scaler',
  resultCd: 'Tens uma marca que funciona — precisas de um sistema que escale sem se partir. Ideal: Pacotes 01, 03 e 06 — linguagem de design e direção criativa como camada contínua.',
  resultD: 'Editorial',
  resultDd: 'Peças editoriais — decks, campanhas, motion. Ideal: Pacotes 05, 06 e 07.',
  resultCta: 'Marcar discovery call',
};

// Spanish — concise, all keys
const es: T = {
  ...en,
  navWork: 'Trabajo', navServices: 'Servicios', navAbout: 'Sobre mí', navContact: 'Contacto',
  navQuiz: '¿Encajamos?', navCta: 'Hablemos',
  status: 'Disponible para nuevos proyectos — 2026',
  heroSub: 'Full Stack Designer y Directora Creativa en Portimão. Creo marcas desde cero — y las reconstruyo para que sean inolvidables.',
  ctaStart: 'Iniciar un proyecto', ctaWork: 'Ver trabajos',
  manifestoLabel: 'Manifiesto',
  manifesto1: 'Cada marca merece', manifesto2: 'un (re)comienzo.',
  manifesto3: 'Un hilo. Una historia. Un principio. Así es Joolomee.',
  servicesLabel: 'Servicios', servicesTitle: 'Lo que hago.', servicesCta: 'Todos los servicios',
  srv01: 'Estrategia e Identidad de Marca',
  srv02: 'Refresh & Rebranding',
  srv03: 'Diseño y Desarrollo Web',
  srv04: 'Diseño UI/UX',
  srv05: 'Redes Sociales & Marketing',
  srv06: 'Dirección Creativa',
  srv07: 'Presentaciones & Motion',
  processLabel: 'Proceso', processTitle: 'Cómo trabajo.',
  p01: 'Escuchar', p02: 'Mapear', p03: 'Explorar', p04: 'Ejecutar', p05: 'Lanzar',
  workLabel: 'Trabajo Seleccionado', workTitle: 'Proyectos destacados.', workCta: 'Ver todo',
  aboutLabel: 'Sobre mí',
  contactLabel: 'Contacto',
  contactTitle1: 'Construyamos', contactTitle2: 'algo', contactTitle3: 'extraordinario.',
  contactWhatsCta: 'Enviar mensaje',
  quizLabel: 'Mini-quiz · 60 segundos', quizTitle: '¿Encajamos?',
  quizSub: 'Cinco preguntas. Al final te digo exactamente cómo puedo ayudarte.',
  quizStart: 'Empezar', quizNext: 'Siguiente', quizBack: 'Volver', quizRestart: 'Repetir',
  quizResult: 'Eres un', resultCta: 'Reservar una llamada',
};

const fr: T = {
  ...en,
  navWork: 'Projets', navServices: 'Services', navAbout: 'À propos', navContact: 'Contact',
  navQuiz: 'On match ?', navCta: 'Parlons',
  status: 'Disponible pour de nouveaux projets — 2026',
  heroSub: 'Full Stack Designer & Directrice Créative à Portimão. Je construis des marques de zéro — et je les reconstruis pour qu\'elles soient inoubliables.',
  ctaStart: 'Démarrer un projet', ctaWork: 'Voir les projets',
  manifestoLabel: 'Manifeste',
  manifesto1: 'Chaque marque mérite', manifesto2: 'un (re)commencement.',
  manifesto3: 'Un fil. Une histoire. Un début. C\'est la méthode Joolomee.',
  servicesLabel: 'Services', servicesTitle: 'Ce que je fais.', servicesCta: 'Tous les services',
  srv01: 'Stratégie & Identité de Marque',
  srv02: 'Refresh & Rebranding',
  srv03: 'Design & Développement Web',
  srv04: 'Design UI/UX',
  srv05: 'Social Media & Marketing',
  srv06: 'Direction Créative',
  srv07: 'Présentations & Motion',
  processLabel: 'Processus', processTitle: 'Comment je travaille.',
  p01: 'Écouter', p02: 'Cartographier', p03: 'Explorer', p04: 'Exécuter', p05: 'Lancer',
  workLabel: 'Travaux Sélectionnés', workTitle: 'Projets en vedette.', workCta: 'Tout voir',
  aboutLabel: 'À propos',
  contactLabel: 'Contact',
  contactTitle1: 'Construisons', contactTitle2: 'quelque chose', contactTitle3: 'd\'extraordinaire.',
  contactWhatsCta: 'Envoyer un message',
  quizLabel: 'Mini-quiz · 60 secondes', quizTitle: 'On match ?',
  quizSub: 'Cinq questions. À la fin, je vous dis exactement comment je peux aider.',
  quizStart: 'Commencer', quizNext: 'Suivant', quizBack: 'Retour', quizRestart: 'Recommencer',
  quizResult: 'Vous êtes', resultCta: 'Réserver un appel',
};

const de: T = {
  ...en,
  navWork: 'Arbeiten', navServices: 'Leistungen', navAbout: 'Über mich', navContact: 'Kontakt',
  navQuiz: 'Passen wir?', navCta: 'Sprechen',
  status: 'Verfügbar für neue Projekte — 2026',
  heroSub: 'Full Stack Designerin & Creative Director in Portimão. Ich baue Marken von Grund auf — und gestalte sie neu, damit sie unvergesslich werden.',
  ctaStart: 'Projekt starten', ctaWork: 'Arbeiten ansehen',
  manifestoLabel: 'Manifest',
  manifesto1: 'Jede Marke verdient', manifesto2: 'einen (Neu)anfang.',
  manifesto3: 'Ein Faden. Eine Geschichte. Ein Anfang. So arbeitet Joolomee.',
  servicesLabel: 'Leistungen', servicesTitle: 'Was ich tue.', servicesCta: 'Alle Leistungen',
  srv01: 'Markenstrategie & Identität',
  srv02: 'Refresh & Rebranding',
  srv03: 'Webdesign & Entwicklung',
  srv04: 'UI/UX Design',
  srv05: 'Social Media & Marketing',
  srv06: 'Creative Direction',
  srv07: 'Präsentationen & Motion',
  processLabel: 'Prozess', processTitle: 'Wie ich arbeite.',
  p01: 'Zuhören', p02: 'Kartieren', p03: 'Erforschen', p04: 'Umsetzen', p05: 'Starten',
  workLabel: 'Ausgewählte Arbeiten', workTitle: 'Ausgewählte Projekte.', workCta: 'Alles ansehen',
  aboutLabel: 'Über mich',
  contactLabel: 'Kontakt',
  contactTitle1: 'Lass uns', contactTitle2: 'etwas', contactTitle3: 'Außergewöhnliches bauen.',
  contactWhatsCta: 'Nachricht senden',
  quizLabel: 'Mini-Quiz · 60 Sekunden', quizTitle: 'Passen wir zusammen?',
  quizSub: 'Fünf Fragen. Am Ende sage ich Ihnen genau, wie ich helfen kann.',
  quizStart: 'Starten', quizNext: 'Weiter', quizBack: 'Zurück', quizRestart: 'Neu starten',
  quizResult: 'Sie sind', resultCta: 'Gespräch buchen',
};

const it: T = {
  ...en,
  navWork: 'Lavori', navServices: 'Servizi', navAbout: 'Chi sono', navContact: 'Contatto',
  navQuiz: 'Ci troviamo?', navCta: 'Parliamo',
  status: 'Disponibile per nuovi progetti — 2026',
  heroSub: 'Full Stack Designer e Direttrice Creativa a Portimão. Creo brand da zero — e li ricostruisco per renderli indimenticabili.',
  ctaStart: 'Inizia un progetto', ctaWork: 'Vedi lavori',
  manifestoLabel: 'Manifesto',
  manifesto1: 'Ogni brand merita', manifesto2: 'un (ri)inizio.',
  manifesto3: 'Un filo. Una storia. Un principio. È il metodo Joolomee.',
  servicesLabel: 'Servizi', servicesTitle: 'Cosa faccio.', servicesCta: 'Tutti i servizi',
  srv01: 'Strategia & Identità di Brand',
  srv02: 'Refresh & Rebranding',
  srv03: 'Web Design & Sviluppo',
  srv04: 'UI/UX Design',
  srv05: 'Social Media & Marketing',
  srv06: 'Direzione Creativa',
  srv07: 'Presentazioni & Motion',
  processLabel: 'Processo', processTitle: 'Come lavoro.',
  p01: 'Ascoltare', p02: 'Mappare', p03: 'Esplorare', p04: 'Realizzare', p05: 'Lanciare',
  workLabel: 'Lavoro Selezionato', workTitle: 'Progetti in evidenza.', workCta: 'Vedi tutti',
  aboutLabel: 'Chi sono',
  contactLabel: 'Contatto',
  contactTitle1: 'Costruiamo', contactTitle2: 'qualcosa', contactTitle3: 'di straordinario.',
  contactWhatsCta: 'Invia messaggio',
  quizLabel: 'Mini-quiz · 60 secondi', quizTitle: 'Siamo compatibili?',
  quizSub: 'Cinque domande. Alla fine ti dico esattamente come posso aiutare.',
  quizStart: 'Inizia', quizNext: 'Avanti', quizBack: 'Indietro', quizRestart: 'Ricomincia',
  quizResult: 'Sei un', resultCta: 'Prenota una call',
};

const nl: T = {
  ...en,
  navWork: 'Werk', navServices: 'Diensten', navAbout: 'Over mij', navContact: 'Contact',
  navQuiz: 'Klikt het?', navCta: 'Praten',
  status: 'Beschikbaar voor nieuwe projecten — 2026',
  heroSub: 'Full Stack Designer & Creative Director in Portimão. Ik bouw merken van de grond af op — en bouw ze opnieuw op om onvergetelijk te zijn.',
  ctaStart: 'Project starten', ctaWork: 'Werk bekijken',
  manifestoLabel: 'Manifest',
  manifesto1: 'Elk merk verdient', manifesto2: 'een (her)start.',
  manifesto3: 'Een draad. Een verhaal. Een begin. Zo werkt Joolomee.',
  servicesLabel: 'Diensten', servicesTitle: 'Wat ik doe.', servicesCta: 'Alle diensten',
  srv01: 'Merkstrategie & Identiteit',
  srv02: 'Refresh & Rebranding',
  srv03: 'Webdesign & Ontwikkeling',
  srv04: 'UI/UX Design',
  srv05: 'Social Media & Marketing',
  srv06: 'Creative Direction',
  srv07: 'Presentaties & Motion',
  processLabel: 'Proces', processTitle: 'Hoe ik werk.',
  p01: 'Luisteren', p02: 'Karteren', p03: 'Verkennen', p04: 'Maken', p05: 'Lanceren',
  workLabel: 'Geselecteerd Werk', workTitle: 'Uitgelichte projecten.', workCta: 'Alle werk',
  aboutLabel: 'Over mij',
  contactLabel: 'Contact',
  contactTitle1: 'Laten we', contactTitle2: 'iets', contactTitle3: 'buitengewoons bouwen.',
  contactWhatsCta: 'Bericht sturen',
  quizLabel: 'Mini-quiz · 60 seconden', quizTitle: 'Klikt het?',
  quizSub: 'Vijf vragen. Daarna vertel ik precies hoe ik kan helpen.',
  quizStart: 'Start', quizNext: 'Volgende', quizBack: 'Terug', quizRestart: 'Opnieuw',
  quizResult: 'Je bent een', resultCta: 'Plan een gesprek',
};

export const COPY: Record<Locale, T> = { en, pt, es, fr, de, it, nl };

export function detectLocaleFromCountry(country?: string): Locale {
  if (!country) return 'en';
  const up = country.toUpperCase();
  for (const [code, meta] of Object.entries(LOCALE_META)) {
    if (meta.countries.includes(up)) return code as Locale;
  }
  return 'en';
}
