export const SITE = {
  name: 'Joolomee',
  tagline: 'Remember me, Joolomee.',
  promise: 'Every brand deserves a (re)start.',
  domain: 'joolomee.com',
  email: 'rememberme@joolomee.com',
  phone: '+351 928 289 201',
  whatsapp: '351928289201',
  location: 'Portimão, Algarve, Portugal',
  linkedin: 'https://www.linkedin.com/in/joana-lopes-mesquita',
  behance: 'https://www.behance.net/joolomee',
  instagram: 'https://www.instagram.com/joolomee',
};

export const NAV_LINKS = [
  { href: '/work', key: 'work' },
  { href: '/services', key: 'services' },
  { href: '/about', key: 'about' },
];

export const CLIENTS = [
  'CogniFit',
  "D'ALMA® FarmLiving",
  'TCPI International',
  'DualClinic Saldanha',
  'CarlaGonçalves',
  'Agência Modal',
  'Albinet',
];

export const SERVICES = [
  { n: '01', title: 'Brand Strategy & Identity', desc: 'Creation of a brand from the ground up — naming, positioning, brand architecture, logo, complete visual system, brand book.' },
  { n: '02', title: 'Brand Refresh & Rebrand', desc: 'Reformulating existing brands to make them memorable, relevant, and ready for the next chapter.' },
  { n: '03', title: 'Web Design & Development', desc: 'Native sites (Next.js / HTML-CSS-JS) and Webflow — corporate, portfolio, landing pages, e-commerce.' },
  { n: '04', title: 'UI/UX Design', desc: 'Interfaces for apps, dashboards, platforms — Figma, Adobe XD, A/B testing, responsive systems.' },
  { n: '05', title: 'Social Media & Marketing Design', desc: 'Templates, B2C campaigns, stories, banners, and ads across Instagram, LinkedIn, and Facebook.' },
  { n: '06', title: 'Creative Direction', desc: 'Visual direction for campaigns, project identity, and production supervision.' },
  { n: '07', title: 'Presentation & Motion', desc: 'Pitch decks, corporate presentations, video editing, motion graphics.' },
];

export type Project = {
  slug: string; client: string; title: string; category: string; year: string;
  tags: string[]; hero: string; accent: string;
};

export const WORK: Project[] = [
  {
    slug: 'cognifit-longevity',
    client: 'CogniFit',
    title: 'Cognitive Health Platform — Longevity',
    category: 'Web Design & Development',
    year: '2022 — 2026',
    tags: ['Landing Pages', 'Responsive Web', 'Marketing Design', 'Campaign Banners'],
    hero: '/work/cognifit-womens-day.jpg',
    accent: 'from-[#0B3B8C] via-[#1A73E8] to-[#6FB6FF]',
  },
  {
    slug: 'dalma-farmliving',
    client: "D'ALMA® FarmLiving",
    title: 'Luxury Farm Hotel & Bio Commerce',
    category: 'Brand Identity',
    year: '2025',
    tags: ['Logo', 'Brand System', 'Packaging', 'Applications'],
    hero: '/work/dalma-mel.jpg',
    accent: 'from-[#2F4F4A] via-[#5C7A70] to-[#B89F6A]',
  },
  {
    slug: 'tcpi-international',
    client: 'TCPI International',
    title: 'Corporate Communications — Deck & Motion',
    category: 'Presentation & Motion',
    year: '2026',
    tags: ['21-slide Deck', 'Motion Video', 'Brand Design'],
    hero: '',
    accent: 'from-[#0F0F10] via-[#2A2A2E] to-[#5C5C66]',
  },
  {
    slug: 'dualclinic-saldanha',
    client: 'DualClinic Saldanha',
    title: 'Aesthetic Clinic Campaigns',
    category: 'Creative Direction',
    year: '2022 — 2023',
    tags: ['Social Media', 'B2C Campaigns', 'Ad Design'],
    hero: '',
    accent: 'from-[#7A1F4F] via-[#C8477E] to-[#FFB3D1]',
  },
  {
    slug: 'carlagoncalves',
    client: 'CarlaGonçalves',
    title: 'Estética & Bem Estar — Brand Identity',
    category: 'Branding',
    year: '2019 — ongoing',
    tags: ['Concept', 'Logo', 'Visual Identity', 'Applications'],
    hero: '',
    accent: 'from-[#2A1B3D] via-[#6B4E8F] to-[#E8C4E8]',
  },
  {
    slug: 'agencia-modal',
    client: 'Agência Modal',
    title: 'Porto Event — Campaign & Merchandise',
    category: 'Graphic Design',
    year: '2024',
    tags: ['Banners', 'Posters', 'Photo Editing', 'Merch'],
    hero: '',
    accent: 'from-[#1F3A5F] via-[#4C6B8A] to-[#A8C6E8]',
  },
  {
    slug: 'albinet',
    client: 'Albinet — Digital Innovation',
    title: 'UX/UI, Web & Interior Design',
    category: 'Multi-discipline',
    year: '2021 — 2022',
    tags: ['UX/UI', 'A/B Testing', 'Landing Pages', '3D · Blender', 'AutoCAD'],
    hero: '',
    accent: 'from-[#0A1F3A] via-[#1A4580] to-[#3D7BC8]',
  },
];

export const STATS = [
  { n: '7+', label: 'Years' },
  { n: '10+', label: 'Brands' },
  { n: '3', label: 'Countries' },
  { n: '22', label: 'Languages · CogniFit' },
];

// i18n ----------------------------------------------------------------
export const LOCALES = ['en', 'pt', 'es', 'fr', 'de', 'it', 'nl'] as const;
export type Locale = (typeof LOCALES)[number];

export const LOCALE_META: Record<Locale, { label: string; native: string; flag: string; countries: string[] }> = {
  en: { label: 'English',    native: 'English',    flag: '🇬🇧', countries: ['GB','US','IE','AU','CA','NZ'] },
  pt: { label: 'Portuguese', native: 'Português',  flag: '🇵🇹', countries: ['PT','BR','AO','MZ','CV'] },
  es: { label: 'Spanish',    native: 'Español',    flag: '🇪🇸', countries: ['ES','MX','AR','CL','CO','PE'] },
  fr: { label: 'French',     native: 'Français',   flag: '🇫🇷', countries: ['FR','BE','CH','LU','MC'] },
  de: { label: 'German',     native: 'Deutsch',    flag: '🇩🇪', countries: ['DE','AT','CH','LI'] },
  it: { label: 'Italian',    native: 'Italiano',   flag: '🇮🇹', countries: ['IT','SM','VA'] },
  nl: { label: 'Dutch',      native: 'Nederlands', flag: '🇳🇱', countries: ['NL','BE','SR'] },
};

export const COPY: Record<Locale, Record<string, string>> = {
  en: {
    status: 'Available for new projects — 2026',
    heroLine1: 'Remember me,',
    heroLine2: 'Joolomee.',
    heroSub: 'Full Stack Designer & Creative Director based in Portimão. I build brands from the ground up — and rebuild them to be unforgettable.',
    ctaStart: 'Start a project',
    ctaWork: 'View work',
    manifestoLabel: 'Manifesto',
    manifesto1: 'Every brand deserves',
    manifesto2: 'a (re)start.',
    manifesto3: 'A thread. A story. A beginning.',
    servicesLabel: 'Services',
    servicesTitle: 'What I do.',
    servicesCta: 'Explore all services',
    workLabel: 'Selected Work',
    workTitle: 'Featured projects.',
    workCta: 'View all work',
    aboutLabel: 'About',
    aboutLead: "I'm Joana — designer, developer, and creative director. I work at the intersection of brand, code, and craft.",
    aboutBody: 'Seven years building visual systems for brands that want to matter. From cognitive-health platforms translated into 22 languages, to luxury farm hotels, to corporate decks — every project is treated as a portfolio piece.',
    aboutCta: 'More about me',
    contactLabel: 'Contact',
    contactTitle1: "Let's build",
    contactTitle2: 'something',
    contactTitle3: 'extraordinary.',
    contactSub: 'Available for new projects — remote worldwide. Full stack from concept to launch.',
    navWork: 'Work', navServices: 'Services', navAbout: 'About', navContact: 'Contact',
    navCta: "Let's talk",
  },
  pt: {
    status: 'Disponível para novos projetos — 2026',
    heroLine1: 'Remember me,',
    heroLine2: 'Joolomee.',
    heroSub: 'Full Stack Designer e Diretora Criativa, em Portimão. Construo marcas de raiz — e reconstruo-as para serem memoráveis.',
    ctaStart: 'Começar um projeto',
    ctaWork: 'Ver trabalhos',
    manifestoLabel: 'Manifesto',
    manifesto1: 'Cada marca merece',
    manifesto2: 'um (re)começo.',
    manifesto3: 'Um fio. Uma história. Um princípio.',
    servicesLabel: 'Serviços',
    servicesTitle: 'O que faço.',
    servicesCta: 'Ver todos os serviços',
    workLabel: 'Trabalho Selecionado',
    workTitle: 'Projetos em destaque.',
    workCta: 'Ver todos os trabalhos',
    aboutLabel: 'Sobre',
    aboutLead: 'Sou a Joana — designer, developer e diretora criativa. Trabalho na interseção entre marca, código e detalhe.',
    aboutBody: 'Sete anos a construir sistemas visuais para marcas que querem importar. De plataformas de saúde cognitiva traduzidas em 22 línguas, a hotéis rurais de luxo, a decks corporativos — cada projeto é tratado como uma peça de portfólio.',
    aboutCta: 'Saber mais sobre mim',
    contactLabel: 'Contacto',
    contactTitle1: 'Vamos construir',
    contactTitle2: 'algo',
    contactTitle3: 'extraordinário.',
    contactSub: 'Disponível para novos projetos — remoto mundialmente. Full stack do conceito ao lançamento.',
    navWork: 'Trabalho', navServices: 'Serviços', navAbout: 'Sobre', navContact: 'Contacto',
    navCta: 'Falar',
  },
  es: {
    status: 'Disponible para nuevos proyectos — 2026',
    heroLine1: 'Remember me,',
    heroLine2: 'Joolomee.',
    heroSub: 'Full Stack Designer y Directora Creativa en Portimão. Creo marcas desde cero — y las reconstruyo para que sean inolvidables.',
    ctaStart: 'Iniciar un proyecto',
    ctaWork: 'Ver trabajos',
    manifestoLabel: 'Manifiesto',
    manifesto1: 'Cada marca merece',
    manifesto2: 'un (re)comienzo.',
    manifesto3: 'Un hilo. Una historia. Un principio.',
    servicesLabel: 'Servicios',
    servicesTitle: 'Lo que hago.',
    servicesCta: 'Explorar todos los servicios',
    workLabel: 'Trabajo Seleccionado',
    workTitle: 'Proyectos destacados.',
    workCta: 'Ver todo el trabajo',
    aboutLabel: 'Sobre mí',
    aboutLead: 'Soy Joana — diseñadora, desarrolladora y directora creativa. Trabajo en la intersección entre marca, código y detalle.',
    aboutBody: 'Siete años construyendo sistemas visuales para marcas que quieren importar. Desde plataformas de salud cognitiva en 22 idiomas hasta hoteles rurales de lujo.',
    aboutCta: 'Más sobre mí',
    contactLabel: 'Contacto',
    contactTitle1: 'Construyamos',
    contactTitle2: 'algo',
    contactTitle3: 'extraordinario.',
    contactSub: 'Disponible para nuevos proyectos — remoto worldwide.',
    navWork: 'Trabajo', navServices: 'Servicios', navAbout: 'Sobre', navContact: 'Contacto',
    navCta: 'Hablemos',
  },
  fr: {
    status: 'Disponible pour de nouveaux projets — 2026',
    heroLine1: 'Remember me,',
    heroLine2: 'Joolomee.',
    heroSub: 'Full Stack Designer & Directrice Créative à Portimão. Je construis des marques de zéro — et je les reconstruis pour qu\'elles soient inoubliables.',
    ctaStart: 'Démarrer un projet',
    ctaWork: 'Voir les projets',
    manifestoLabel: 'Manifeste',
    manifesto1: 'Chaque marque mérite',
    manifesto2: 'un (re)commencement.',
    manifesto3: 'Un fil. Une histoire. Un début.',
    servicesLabel: 'Services',
    servicesTitle: 'Ce que je fais.',
    servicesCta: 'Voir tous les services',
    workLabel: 'Travaux Sélectionnés',
    workTitle: 'Projets en vedette.',
    workCta: 'Voir tous les travaux',
    aboutLabel: 'À propos',
    aboutLead: 'Je suis Joana — designer, développeuse et directrice créative.',
    aboutBody: 'Sept ans à construire des systèmes visuels pour des marques qui veulent compter.',
    aboutCta: 'En savoir plus',
    contactLabel: 'Contact',
    contactTitle1: 'Construisons',
    contactTitle2: 'quelque chose',
    contactTitle3: 'd\'extraordinaire.',
    contactSub: 'Disponible pour de nouveaux projets — remote mondial.',
    navWork: 'Travaux', navServices: 'Services', navAbout: 'À propos', navContact: 'Contact',
    navCta: 'Parlons',
  },
  de: {
    status: 'Verfügbar für neue Projekte — 2026',
    heroLine1: 'Remember me,',
    heroLine2: 'Joolomee.',
    heroSub: 'Full Stack Designerin & Creative Director in Portimão. Ich baue Marken von Grund auf — und gestalte sie neu, damit sie unvergesslich werden.',
    ctaStart: 'Projekt starten',
    ctaWork: 'Arbeiten ansehen',
    manifestoLabel: 'Manifest',
    manifesto1: 'Jede Marke verdient',
    manifesto2: 'einen (Neu)anfang.',
    manifesto3: 'Ein Faden. Eine Geschichte. Ein Anfang.',
    servicesLabel: 'Leistungen',
    servicesTitle: 'Was ich tue.',
    servicesCta: 'Alle Leistungen',
    workLabel: 'Ausgewählte Arbeiten',
    workTitle: 'Ausgewählte Projekte.',
    workCta: 'Alle Arbeiten',
    aboutLabel: 'Über mich',
    aboutLead: 'Ich bin Joana — Designerin, Entwicklerin und Creative Director.',
    aboutBody: 'Sieben Jahre visuelle Systeme für Marken, die zählen wollen.',
    aboutCta: 'Mehr über mich',
    contactLabel: 'Kontakt',
    contactTitle1: 'Lass uns',
    contactTitle2: 'etwas',
    contactTitle3: 'Außergewöhnliches bauen.',
    contactSub: 'Verfügbar für neue Projekte — weltweit remote.',
    navWork: 'Arbeiten', navServices: 'Leistungen', navAbout: 'Über', navContact: 'Kontakt',
    navCta: 'Sprechen',
  },
  it: {
    status: 'Disponibile per nuovi progetti — 2026',
    heroLine1: 'Remember me,',
    heroLine2: 'Joolomee.',
    heroSub: 'Full Stack Designer e Direttrice Creativa a Portimão. Creo brand da zero — e li ricostruisco per renderli indimenticabili.',
    ctaStart: 'Iniziare un progetto',
    ctaWork: 'Vedi lavori',
    manifestoLabel: 'Manifesto',
    manifesto1: 'Ogni brand merita',
    manifesto2: 'un (ri)inizio.',
    manifesto3: 'Un filo. Una storia. Un principio.',
    servicesLabel: 'Servizi',
    servicesTitle: 'Cosa faccio.',
    servicesCta: 'Esplora tutti i servizi',
    workLabel: 'Lavoro Selezionato',
    workTitle: 'Progetti in evidenza.',
    workCta: 'Vedi tutti i lavori',
    aboutLabel: 'Chi sono',
    aboutLead: 'Sono Joana — designer, sviluppatrice e direttrice creativa.',
    aboutBody: 'Sette anni costruendo sistemi visivi per brand che vogliono contare.',
    aboutCta: 'Di più su di me',
    contactLabel: 'Contatto',
    contactTitle1: 'Costruiamo',
    contactTitle2: 'qualcosa',
    contactTitle3: 'di straordinario.',
    contactSub: 'Disponibile per nuovi progetti — remoto worldwide.',
    navWork: 'Lavoro', navServices: 'Servizi', navAbout: 'Chi sono', navContact: 'Contatto',
    navCta: 'Parliamo',
  },
  nl: {
    status: 'Beschikbaar voor nieuwe projecten — 2026',
    heroLine1: 'Remember me,',
    heroLine2: 'Joolomee.',
    heroSub: 'Full Stack Designer & Creative Director in Portimão. Ik bouw merken van de grond af op — en bouw ze opnieuw op om onvergetelijk te zijn.',
    ctaStart: 'Project starten',
    ctaWork: 'Werk bekijken',
    manifestoLabel: 'Manifest',
    manifesto1: 'Elk merk verdient',
    manifesto2: 'een (her)start.',
    manifesto3: 'Een draad. Een verhaal. Een begin.',
    servicesLabel: 'Diensten',
    servicesTitle: 'Wat ik doe.',
    servicesCta: 'Alle diensten',
    workLabel: 'Geselecteerd Werk',
    workTitle: 'Uitgelichte projecten.',
    workCta: 'Alle werk',
    aboutLabel: 'Over mij',
    aboutLead: 'Ik ben Joana — designer, developer en creative director.',
    aboutBody: 'Zeven jaar visuele systemen bouwen voor merken die ertoe willen doen.',
    aboutCta: 'Meer over mij',
    contactLabel: 'Contact',
    contactTitle1: 'Laten we',
    contactTitle2: 'iets',
    contactTitle3: 'buitengewoons bouwen.',
    contactSub: 'Beschikbaar voor nieuwe projecten — remote wereldwijd.',
    navWork: 'Werk', navServices: 'Diensten', navAbout: 'Over', navContact: 'Contact',
    navCta: 'Praten',
  },
};

export function detectLocaleFromCountry(country?: string): Locale {
  if (!country) return 'en';
  const up = country.toUpperCase();
  for (const [code, meta] of Object.entries(LOCALE_META)) {
    if (meta.countries.includes(up)) return code as Locale;
  }
  return 'en';
}
